//! Lifecycle commands: init (scaffold the board), seed (arte's own dogfood),
//! suggest_bootstrap (empty-board nudge), brief (print a role's prompt).
//!
//! These are the FIRST commands an agent encounters — they're the entry point.

use std::env;
use std::fs;
use std::path::Path;

use crate::*;

/// `arte init [--template software|arte]` — scaffold arte.toml + .truth/ +
/// AGENTS.md. Idempotent: never clobbers a project's existing AGENTS.md that
/// wasn't ours to begin with.
pub fn cmd_init() {
    let mut args = env::args().skip(2);
    let mut tmpl = "software".to_string();
    while let Some(a) = args.next() {
        if a == "--template" {
            match args.next() {
                Some(v) => tmpl = v,
                None => {
                    eprintln!("--template requires a value (software | arte)");
                    std::process::exit(2);
                }
            }
        }
    }
    let Some(toml) = resolve_template(&tmpl) else {
        eprintln!("unknown template '{tmpl}' — built-in: software | arte");
        std::process::exit(2);
    };
    if !Path::new("arte.toml").exists() {
        if let Err(e) = fs::write("arte.toml", &toml) {
            eprintln!("could not write arte.toml: {e}");
            std::process::exit(1);
        }
        println!("• wrote arte.toml (template: {tmpl})");
    }
    if let Err(e) = fs::create_dir_all(TRUTH_DIR) {
        eprintln!("could not create {}: {e}", TRUTH_DIR);
        std::process::exit(1);
    }
    let seeded = fs::read_dir(TRUTH_DIR).map(|d| d.flatten().any(|e| e.path().extension().map(|x| x == "node").unwrap_or(false))).unwrap_or(false);
    if tmpl == "arte" && !seeded {
        seed_arte();
        println!("• seeded arte's own design truth (11 nodes)");
    }
    if tmpl == "software" {
        print!("{SOFTWARE_GUIDE}");
    }
    // AGENTS.md — the cross-agent instruction file (Claude Code, Codex, … read it
    // on first contact). Generated from the SAME guide the binary prints, so it
    // can't drift; regenerated on every init. Skipped if the project already has
    // one that isn't ours (never clobber a human's file).
    let agents_hdr = "<!-- generated by `arte init` — do not edit; re-run init to refresh -->\n";
    let ours = fs::read_to_string("AGENTS.md").map(|s| s.starts_with(agents_hdr)).unwrap_or(true);
    if ours {
        let mut body = format!(
            "{agents_hdr}\n# This project runs on an arte design-truth board\n\n\
Before ANY work: run `arte observe` to read the board. The protocol below is\n\
binding — the CI gate (`arte gate`) fails work that skips it.\n\n\
SETUP: if `arte` is not on PATH, build it from the arte repo:\n\
  git clone <arte repo> && cd arte && cargo build --release --workspace\n\
  cp target/release/arte target/release/arte-tui ~/.local/bin/\n\
VIEWER (optional, for the human's split pane): `arte view` opens the live board\n\
TUI (delegates to the `arte-tui` binary; refreshes as you edit; `arte working <id>`\n\
makes the node you're on PULSE there — declare your focus).\n\n\
{AGENT_GUIDE}"
        );
        if tmpl == "software" { body.push_str(SOFTWARE_GUIDE); }
        if let Err(e) = fs::write("AGENTS.md", body) {
            eprintln!("could not write AGENTS.md: {e}");
            std::process::exit(1);
        }
        println!("• wrote AGENTS.md (first-contact protocol for any agent)");
    }
    println!("done. try: arte observe");
}

/// arte's own dogfood — the design truth that arte ships with for itself.
/// Only seeded by `--template arte`.
fn seed_arte() {
    write_node("i1", "intent", "who", "", "AI agents that build, and the humans who review them", &[]);
    write_node("i2", "intent", "why", "", "AI-built code is untraceable without a shared design contract", &[]);
    write_node("i3", "intent", "jobs", "", "Record why code exists and prove it still matches", &[]);
    write_node("i3a", "intent", "jobs", "i3", "Capture the intent behind each change", &[]);
    write_node("i3b", "intent", "jobs", "i3", "Prove the code still matches its intent", &[]);
    write_node("i4", "intent", "constraints", "", "Domain-agnostic: roles and subsets are declared, not hardcoded", &[]);
    write_node("m1", "impl", "storage", "", "Node reader/writer (.truth/<id>.node)", &["i3b"]);
    write_node("c1", "control", "identity", "", "A node is keyed by a stable id, never by its title", &["i3"]);
    write_node("c2", "control", "storage", "", "One node per file; git merges per node natively", &["i3"]);
    write_node("c3", "control", "format", "", "Line-oriented key:value, so git's line merge reconciles per field", &["i3"]);
    write_node("c4", "control", "agnostic", "", "Layers and subsets come from arte.toml, so the tool stays agnostic", &["i4"]);
}

/// Empty-repo guide, emitted when `arte`/`arte observe` finds no nodes. The
/// agent's read channel is empty → tell it exactly how to bootstrap.
pub fn suggest_bootstrap() {
    println!("new to arte? run:  arte guide\n");
    if Path::new("arte.toml").exists() {
        println!("arte board initialized, no nodes yet.\n");
        println!("map the design — each layer serves the one above:");
        println!("  arte add intent \"<what & why>\"");
        println!("  arte add impl \"<how>\"          --serves <intent-id>");
        println!("  arte add control \"<rule/limit>\" --serves <impl-id>");
        println!("  arte add validation \"<proof>\"   --serves <control-id>");
        println!("\nthen: arte (view) · arte coverage (gaps) · arte trace <id>");
    } else {
        println!("no arte board here (.truth/ not found).\n");
        println!("initialize one:");
        println!("  arte init                        software (default)");
        println!("  arte init --template arte");
        println!("\nthen run `arte` again — it'll guide the next step.");
    }
}

/// `arte brief <role>` — print a role's full WORKING BRIEF for direct prompting.
/// Ambient docs (AGENTS.md) don't reliably drive weak agents; a brief piped
/// into the prompt does (measured: lab batch v4 — guidance in AGENTS.md alone
/// collapsed spec depth 31→13 controls and let 10 qa bugs through).
pub fn cmd_brief() {
    let Some(role) = env::args().nth(2) else {
        eprintln!("usage: arte brief <role>   (specifier|test-author|implementer|qa — aliases accepted)");
        std::process::exit(2);
    };
    // role_lane recognises the aliases (spec/specifier, tester/adversary, impl/implementer);
    // let it be the single source of truth for "what is a role?" rather than re-validating here.
    print!("{}", role_lane(&role));
}